// =============================================================================
// GermaniaApp — Excel → SQL member importer
// Reads a member list (.xlsx) and generates supabase/members_import.sql, which
// you run in the Supabase SQL editor. Imported members are created HIDDEN and
// UNCLAIMED (consented = false, auth_user_id = null): nobody sees them until the
// person signs in, claims their row by verified phone, and opts in.
//
// Usage (on your machine, not in this sandbox):
//   npm install xlsx
//   node scripts/import-members.mjs "path/to/members.xlsx" [SheetName]
//
// Edit COLUMN_MAP below so the values match YOUR spreadsheet's header names.
// =============================================================================
import * as XLSX from 'xlsx';
import { writeFileSync } from 'node:fs';

// --- map our fields  ->  your column headers (change the right-hand strings) --
const COLUMN_MAP = {
  salutation: 'Anrede',
  first_name: 'Vorname',
  last_name: 'Nachname',
  email: 'E-Mail',
  phone: 'Telefon',          // claim key — must be the person's own mobile
  date_of_birth: 'Geburtsdatum',
  date_of_death: 'Todesdatum',
  gender: 'Geschlecht',
  street: 'Straße',
  postal_code: 'PLZ',
  city: 'Stadt',
  country_code: 'Land',      // ISO-2, e.g. DE
  profession: 'Beruf',
  trivia: 'Trivia',
  deceased: 'Verstorben',    // any non-empty value / 'ja' / 'x' => deceased
};

const [, , file, sheetName] = process.argv;
if (!file) {
  console.error('Usage: node scripts/import-members.mjs <file.xlsx> [SheetName]');
  process.exit(1);
}

const wb = XLSX.readFile(file, { cellDates: true });
const ws = wb.Sheets[sheetName || wb.SheetNames[0]];
const rows = XLSX.utils.sheet_to_json(ws, { defval: '' });

const q = (v) => (v == null || v === '' ? 'null' : `'${String(v).trim().replace(/'/g, "''")}'`);
const isoDate = (v) => {
  if (!v) return null;
  const d = v instanceof Date ? v : new Date(v);
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
};
const gender = (v) => {
  const s = String(v || '').toLowerCase();
  if (s.startsWith('m') || s.includes('männ')) return 'male';
  if (s.startsWith('w') || s.startsWith('f') || s.includes('weib')) return 'female';
  return s ? 'other' : null;
};
const get = (row, key) => row[COLUMN_MAP[key]];

let out = `-- Generated by scripts/import-members.mjs — ${rows.length} rows.
-- Members are HIDDEN + UNCLAIMED until they claim (by phone) and opt in.
-- Run in the Supabase SQL editor AFTER schema.sql.\n\n`;

let n = 0;
for (const row of rows) {
  const first = get(row, 'first_name');
  const last = get(row, 'last_name');
  if (!first && !last) continue; // skip blank lines
  const deceased = String(get(row, 'deceased') || '').trim() !== '';
  const status = deceased ? 'deceased' : 'active';
  const dob = isoDate(get(row, 'date_of_birth')) || '1900-01-01'; // dob is required
  const dod = isoDate(get(row, 'date_of_death'));
  const hasAddr = get(row, 'street') || get(row, 'city') || get(row, 'postal_code');
  const prof = get(row, 'profession');

  out += `do $$\ndeclare mid uuid;\nbegin\n`;
  out += `  insert into member (salutation, first_name, last_name, email, phone, date_of_birth, date_of_death, gender, status, trivia, consented)\n`;
  out += `  values (${q(get(row, 'salutation'))}, ${q(first)}, ${q(last)}, ${q(get(row, 'email'))}, ${q(get(row, 'phone'))}, ${q(dob)}, ${dod ? q(dod) : 'null'}, ${q(gender(get(row, 'gender')))}, '${status}', ${q(get(row, 'trivia'))}, false)\n`;
  out += `  returning id into mid;\n`;
  if (hasAddr) {
    out += `  insert into address (member_id, label, is_primary, street, postal_code, city, country_code)\n`;
    out += `  values (mid, 'home', true, ${q(get(row, 'street'))}, ${q(get(row, 'postal_code'))}, ${q(get(row, 'city'))}, ${q(get(row, 'country_code'))});\n`;
  }
  if (prof) {
    out += `  insert into member_profession (member_id, title, is_primary) values (mid, ${q(prof)}, true);\n`;
  }
  out += `end $$;\n\n`;
  n++;
}

const target = new URL('../supabase/members_import.sql', import.meta.url);
writeFileSync(target, out);
console.log(`Wrote ${n} members to supabase/members_import.sql`);
console.log('Review it, then run it in the Supabase SQL editor.');
